In [3]:
import pandas as pd
df = pd.read_excel(r"C:\Users\Prashant\Downloads\Online_Retail_2009_2010.xlsx")

In [4]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,12/1/2009 7:45,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,12/1/2009 7:45,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,12/1/2009 7:45,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,12/1/2009 7:45,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,12/1/2009 7:45,1.25,13085.0,United Kingdom

In [5]:
df.dtypes

Invoice         object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
Price          float64
Customer ID    float64
Country         object
dtype: object

In [6]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [7]:
df = df.dropna()

In [8]:
df.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [12]:
df = df[df['Quantity']>0]
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,12/1/2009 7:45,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,12/1/2009 7:45,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,12/1/2009 7:45,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,12/1/2009 7:45,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,12/1/2009 7:45,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,12/9/2010 20:01,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,12/9/2010 20:01,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,12/9/2010 20:01,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,12/9/2010 20:01,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,12/9/2010 20:01,1.95,17530.0,United Kingdom

In [13]:
df = df[df['Price']>0]
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,12/1/2009 7:45,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,12/1/2009 7:45,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,12/1/2009 7:45,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,12/1/2009 7:45,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,12/1/2009 7:45,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,12/9/2010 20:01,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,12/9/2010 20:01,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,12/9/2010 20:01,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,12/9/2010 20:01,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,12/9/2010 20:01,1.95,17530.0,United Kingdom

In [14]:
df = df.reset_index(drop=True)

In [15]:
print("\nDataset shape after cleaning:",df.shape)

Dataset shape after cleaning: (407664, 8)

In [16]:
df.to_csv("cleaned_attendance_data.csv", index=False)

In [17]:
df.to_csv("Online_Retail_Cleaned.csv", index=False)

In [18]:
import os
os.getcwd()

'c:\\Users\\Prashant\\.jupyter'

In [19]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Prashant\.jupyter\Online_Retail_Cleaned.csv")
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,12/1/2009 7:45,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,12/1/2009 7:45,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,12/1/2009 7:45,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,12/1/2009 7:45,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,12/1/2009 7:45,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
407659,538171,22271,FELTCRAFT DOLL ROSIE,2,12/9/2010 20:01,2.95,17530.0,United Kingdom
407660,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,12/9/2010 20:01,3.75,17530.0,United Kingdom
407661,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,12/9/2010 20:01,3.75,17530.0,United Kingdom
407662,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,12/9/2010 20:01,3.75,17530.0,United Kingdom
407663,538171,21931,JUMBO STORAGE BAG SUKI,2,12/9/2010 20:01,1.95,17530.0,United Kingdom

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Prashant\.jupyter\Online_Retail_Cleaned.csv")

In [2]:
import pandas as pd
import numpy as np
from datetime import datetime

In [3]:
df['TotalAmount'] = df['Quantity'] * df['Price']
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalAmount
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

In [4]:
snapshot_date = df['InvoiceDate'].max() + pd.Timedelta(days=1)

In [5]:
rfm = df.groupby('Customer ID').agg({
    'InvoiceDate' : lambda x: (snapshot_date - x.max()).days,  
    'Invoice' : 'nunique',
    'TotalAmount' : 'sum'
})

rfm.rename(columns={
    'InvoiceDate' : 'Recency',
    'Invoice' : 'Frequency',
    'TotalAmount' : 'Monetary'
    }, inplace=True)

rfm.head()

             Recency  Frequency  Monetary
Customer ID
12346.0          165         11    372.86
12347.0            3          2   1323.32
12348.0           74          1    222.16
12349.0           43          3   2671.14
12351.0           11          1    300.93

In [6]:
rfm.dtypes

Recency        int64
Frequency      int64
Monetary     float64
dtype: object

In [7]:
rfm['R_Score'] = pd.qcut(rfm['Recency'], 5, labels=[5,4,3,2,1])
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 5, labels=[1,2,3,4,5])
rfm['M_Score'] = pd.qcut(rfm['Monetary'], 5, labels=[1,2,3,4,5])

rfm.head()

             Recency  Frequency  Monetary R_Score F_Score M_Score
Customer ID
12346.0          165         11    372.86       2       5       2
12347.0            3          2   1323.32       5       2       4
12348.0           74          1    222.16       2       1       1
12349.0           43          3   2671.14       3       3       5
12351.0           11          1    300.93       5       1       2

In [8]:
rfm['RFM_Score'] = rfm['R_Score'].astype(str) + \
                   rfm['F_Score'].astype(str) + \
                   rfm['M_Score'].astype(str)

rfm.head()

             Recency  Frequency  Monetary R_Score F_Score M_Score RFM_Score
Customer ID
12346.0          165         11    372.86       2       5       2       252
12347.0            3          2   1323.32       5       2       4       524
12348.0           74          1    222.16       2       1       1       211
12349.0           43          3   2671.14       3       3       5       335
12351.0           11          1    300.93       5       1       2       512

In [ ]:
def segment_customer(row):
    if row['R_Score'] >= 4 and row['F_Score'] >= 4:
        return 'Champions'

    elif row['F_Score'] >= 4:
        return 'Loyalists'

    elif row['R_Score'] <= 2 and row['F_Score'] <= 2:
        return 'Hibernating'

    else:
        return 'Potential'

rfm['Segment'] = rfm.apply(segment_customer, axis=1)

In [19]:
rfm.head()

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Segment
Customer ID,,,,,,,,
12346.0,165,11,372.86,2,5,2,252,Loyalists
12347.0,3,2,1323.32,5,2,4,524,Potential
12348.0,74,1,222.16,2,1,1,211,Hibernating
12349.0,43,3,2671.14,3,3,5,335,Potential
12351.0,11,1,300.93,5,1,2,512,Potential

In [15]:
rfm['Segment'].value_counts()

Segment
Potential      1572
Champions      1105
Hibernating    1015
Loyalists       620
Name: count, dtype: int64

In [16]:
rfm.to_csv("rfm_data.csv", index=False)

In [17]:
import pandas as pd
df = pd.read_csv(r"rfm_data.csv")
df

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Segment
0,165,11,372.86,2,5,2,252,Loyalists
1,3,2,1323.32,5,2,4,524,Potential
2,74,1,222.16,2,1,1,211,Hibernating
3,43,3,2671.14,3,3,5,335,Potential
4,11,1,300.93,5,1,2,512,Potential
...,...,...,...,...,...,...,...,...
4307,18,6,641.77,4,5,3,453,Champions
4308,67,1,461.68,3,2,2,322,Potential
4309,296,1,427.00,1,2,2,122,Hibernating
4310,112,2,1296.43,2,3,4,234,Potential
4311,18,4,2345.71,4,4,5,445,Champions

In [18]:
import os
os.getcwd()

'c:\\Users\\Prashant\\.jupyter'

In [1]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in c:\users\prashant\appdata\local\programs\python\python314\lib\site-packages (2.0.48)
Requirement already satisfied: greenlet>=1 in c:\users\prashant\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\prashant\appdata\roaming\python\python314\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp314-cp314-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 1.1 MB/s eta 0:00:03
   ----------- ---------------------------- 0.8/2.8 MB 1.2 MB/s eta 0:00:02
   -------------- ------------------------- 1.0/2.8 MB 1.2 MB/s eta 0:00:02
   ------------------ --------------------- 1.3/2.8 MB 1.2 MB/s eta 0:00:02
   ---------------------- ----------------- 1.6/2.8 MB 1.2 MB/s eta 0:00:02
   -------------------------- ------------- 1.8/2.8 MB 1.1 MB/s eta 0:00:01
   -------------------------- ------------- 1.8/2.8 MB 1.1 MB/s eta 0:00:01
   -------------------------- ------------- 1.8/2.8 MB 1.1 MB/s eta 0:00:01
   ----------------------------- ---------- 2.1/2.8 MB 951.0 kB/s eta 0:00:01
   --------------------------------- ------ 2.4/2.8 MB 980.8 kB/s eta 0:00:01
   ------------------------------------- -- 2.6/2.8 MB 979.1 kB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 942.9 kB/s  0:00:03
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
import psycopg2

conn = psycopg2.connect(
    dbname = "customer_behaviour",
    user = "postgres",
    password = "Pass123",
    host = "localhost",
    port = "5432"
)

cur = conn.cursor()


cur.close()
conn.close()